docs(rocfft): enable generating llms.txt and fix Doxygen errors (#12044)
## Motivation

- Enable generating llms.txt and llms-full.txt (see https://llmstxt.org)
for LLM-assisted access.

- Fix Doxygen errors

<!-- Explain the purpose of this PR and the goals it aims to achieve.
-->

## Technical Details

- Add `rocm_docs_generate_llms = True` in the Sphinx config

- Also, fix Doxygen errors preventing the docs from building by fixing
undocumented members. (Warnings are treated as fatal per
https://github.com/ROCm/rocm-libraries/blob/develop/projects/rocfft/docs/doxygen/Doxyfile#L744)

    ```bash
    Generating docs for file rocfft.h...

/home/petepark/amd/rocm-libraries/projects/rocfft/library/include/rocfft/rocfft.h:47:
error: Member ROCFFT_DEPRECATED_MSG(msg) (macro definition) of file
rocfft.h is not documented. (warning treated as error, aborting now)
    Exiting...

    Extension error (rocm_docs.doxygen):
Handler <function _run_doxygen at 0x7242028eca60> for event
'config-inited' threw an exception (exception: Failed when running
doxygen)
    ```

   ```bash
    Generating docs for file rocfft.h...

/home/petepark/amd/rocm-libraries/projects/rocfft/library/include/rocfft/rocfft.h:33:
error: Member ROCFFT_EXPORT (macro definition) of file rocfft.h is not
documented. (warning treated as error, aborting now)
    Exiting...

    Extension error (rocm_docs.doxygen):
Handler <function _run_doxygen at 0x7c4e19be4a60> for event
'config-inited' threw an exception (exception: Failed when running
doxygen)
   ```

<!-- Explain the changes along with any relevant GitHub links. -->

## Issue Tracking

ISSUE ID: AIROCDOC-4235

<!-- Include a GitHub Issue and/or JIRA ID. Do not post any full JIRA
links here. -->
<!-- GitHub issue: https://github.com/ROCm/rocm-systems/issues/1234 -->
<!-- JIRA ID: EXAMPLECOMPONENT-1234 -->

## Test Plan

<!-- Explain any relevant testing done to verify this PR. -->

Look at
-
[llms.txt](https://rocm.docs.amd.com/projects/rocFFT/en/users-peterjunpark-rocfft-llmstxt/llms.txt)
-
[llms-full.txt](https://rocm.docs.amd.com/projects/rocFFT/en/users-peterjunpark-rocfft-llmstxt/llms-full.txt)

## Test Result

<!-- Briefly summarize test outcomes. -->

Looks ok. Passes Chrome's Lighthouse audit for agentic browsing:

<img width="1472" height="1230" alt="image"
src="https://github.com/user-attachments/assets/54e7d2e8-6b98-45c2-91d9-fdd0d322375b"
/>

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/rocm-systems/blob/develop/CONTRIBUTING.md.

(cherry picked from commit 06fbe9a1b8dba75a987efe9fca952976198beb8c)