Re-land "fix (rocprim): Update lookback scan and ordered_block_id optimizations to include gfx1250"" (#12608)
Reverts https://github.com/ROCm/rocm-libraries/pull/12593 to re-land
https://github.com/ROCm/rocm-libraries/pull/11620.

### Why it was originally reverted

The JAX build failure reported at
https://github.com/ROCm/rocm-libraries/issues/12598 is due to a critical
bug in the JAX build process:
https://github.com/ROCm/TheRock/issues/8520: JAX is using LLVM from
https://repo.amd.com/rocm/tarball/therock-dist-linux-gfx908-7.12.0.tar.gz,
not the current ROCm install (e.g. what we build from source as part of
each CI/CD run). That results in errors trying to use the newer
`gfx1250-strict` target:

```
2026-09-25 09:17:26,176 - INFO - bazel-out/k8-opt/bin/external/xla++rocm_configure_ext+local_config_rocm/rocm/_virtual_includes/rocm_headers/rocm/include/rocprim/device/detail/config/../../../block/../thread/thread_load.hpp:125:1: error: the argument to __builtin_amdgcn_processor_is must be a valid AMDGCN processor identifier; 'gfx1250-strict' is not valid
...
2026-09-25 09:17:26,180 - INFO - clang++: error: unable to execute command: Segmentation fault (core dumped)
2026-09-25 09:17:26,180 - INFO - clang++: error: clang frontend command failed due to signal (use -v to see invocation)
2026-09-25 09:17:26,180 - INFO - AMD clang version 22.0.0git (https://github.com/ROCm/llvm-project.git c849bc16b0e49951d313756f20b73c2b28d321d7+PATCHED:9a6ac45c97a1e511db838c5b46257324d2de1780)
```

### Why I believe we should proceed anyways

I think we should re-land this change and have JAX builds **remain
broken** for gfx1250 until JAX either
1. Disables builds for gfx1250[-strict]
2. Updates to a more recent compiler (ideally from our current source
build/install)